version: '3'
services:
  advanced-pid-rs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/advanced-pid-rs:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/advanced-pid-rs
    tty: true
    command: sleep inf
    # device access
    privileged: true
